{
 "title": "Twitch Channel Points Miner",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Channel Points",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitch_channel_points", "legendFormat": "{{streamer}}" }
   ]
  },
  {
   "title": "Current Viewer Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitch_streamer_viewers", "legendFormat": "{{streamer}}" }
   ]
  },
  {
   "title": "Streamer Live",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "twitch_streamer_live", "legendFormat": "{{streamer}}" }
   ]
  },
  {
   "title": "Total Streamers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitch_total_streamers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "twitch_total_users", "legendFormat": "{{streamer}}" }
   ]
  }
 ]
}