name: Go CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    branches-ignore:
      - "dependabot/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Install dependencies
        run: go mod tidy

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.3

      - name: Run other linters
        run: go vet ./...

      - name: Run gofmt
        run: gofmt -d -l .

      - name: Run modernize
        run:
          go run
          golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest
          ./...
